name: Windows build and tests
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Build and test binary relay
        shell: powershell
        run: .\build.ps1
      - name: Test installer
        shell: powershell
        run: .\tests\Installer.Tests.ps1
